action_apis = {'Enumeration ': ['CreateToolhelp32Snapshot', 'EnumDeviceDrivers', 'EnumProcesses', 'EnumProcessModules',
                                'EnumProcessModulesEx', 'FindFirstFileA', 'FindNextFileA',
                                'GetLogicalProcessorInformation', 'GetLogicalProcessorInformationEx',
                                'GetModuleBaseNameA', 'GetSystemDefaultLangId', 'GetVersionExA', 'GetWindowsDirectoryA',
                                'IsWoW64Process', 'Module32First', 'Module32Next', 'Process32First', 'Process32Next',
                                'ReadProcessMemory', 'Thread32First', 'Thread32Next', 'GetSystemDirectoryA',
                                'GetSystemTime', 'ReadFile', 'GetComputerNameA', 'VirtualQueryEx',
                                'GetProcessIdOfThread', 'GetProcessId', 'GetCurrentThread', 'GetCurrentThreadId',
                                'GetThreadId', 'GetThreadInformation', 'GetCurrentProcess', 'GetCurrentProcessId',
                                'SearchPathA', 'GetFileTime ', 'GetFileAttributesA ', 'LookupPrivilegeValueA',
                                'LookupAccountNameA', 'GetCurrentHwProfileA', 'GetUserNameA', 'RegEnumKeyExA',
                                'RegEnumKeyExW',
                                'RegEnumValueA', 'RegEnumValueW', 'RegQueryInfoKeyA', 'RegQueryMultipleValuesA',
                                'RegQueryValueExA', 'RegQueryValueExW'
                                                    'NtQueryDirectoryFile', 'NtQueryInformationProcess',
                                'NtQuerySystemEnvironmentValueEx',
                                'EnumDesktopWindows', 'EnumWindows', 'NetShareEnum', 'NetShareGetInfo', 'NetShareCheck',
                                'GetAdaptersInfo', 'PathFileExistsA', 'GetNativeSystemInfo', 'RtlGetVersion',
                                'GetIpNetTable', 'GetLogicalDrives', 'GetDriveTypeA', 'RegEnumKeyA',
                                'WNetEnumResourceA', 'WNetCloseEnum', 'FindFirstUrlCacheEntryA',
                                'FindNextUrlCacheEntryA', 'WNetAddConnection2A', 'WNetAddConnectionA',
                                'EnumResourceTypesA', 'EnumResourceTypesExA', 'GetSystemTimeAsFileTime',
                                'GetThreadLocale', 'EnumSystemLocalesA'],
               'Injection ': ['CreateFileMappingA', 'CreateProcessA', 'CreateRemoteThread', 'CreateRemoteThreadEx',
                              'GetModuleHandleA', 'GetProcAddress', 'GetThreadContext', 'HeapCreate', 'LoadLibraryA',
                              'LoadLibraryW',
                              'LoadLibraryExA', 'LocalAlloc', 'MapViewOfFile', 'MapViewOfFile2', 'MapViewOfFile3',
                              'MapViewOfFileEx', 'OpenThread', 'Process32First', 'Process32Next', 'QueueUserAPC',
                              'ReadProcessMemory', 'ResumeThread', 'SetProcessDEPPolicy', 'SetThreadContext',
                              'SuspendThread', 'Thread32First', 'Thread32Next', 'Toolhelp32ReadProcessMemory',
                              'VirtualAlloc', 'VirtualAllocEx', 'VirtualProtect', 'VirtualProtectEx',
                              'WriteProcessMemory', 'VirtualAllocExNuma', 'VirtualAlloc2', 'VirtualAlloc2FromApp',
                              'VirtualAllocFromApp', 'VirtualProtectFromApp', 'CreateThread', 'WaitForSingleObject ',
                              'OpenProcess', 'OpenFileMappingA', 'GetProcessHeap', 'GetProcessHeaps', 'HeapAlloc',
                              'HeapReAlloc', 'GlobalAlloc', 'AdjustTokenPrivileges', 'CreateProcessAsUserA',
                              'OpenProcessToken', 'CreateProcessWithTokenW', 'NtAdjustPrivilegesToken',
                              'NtAllocateVirtualMemory', 'NtContinue', 'NtCreateProcess', 'NtCreateProcessEx',
                              'NtCreateSection', 'NtCreateThread', 'NtCreateThreadEx', 'NtCreateUserProcess',
                              'NtDuplicateObject', 'NtMapViewOfSection', 'NtOpenProcess', 'NtOpenThread',
                              'NtProtectVirtualMemory', 'NtQueueApcThread', 'NtQueueApcThreadEx', 'NtQueueApcThreadEx2',
                              'NtReadVirtualMemory', 'NtResumeThread', 'NtUnmapViewOfSection',
                              'NtWaitForMultipleObjects', 'NtWaitForSingleObject', 'NtWriteVirtualMemory',
                              'RtlCreateHeap', 'LdrLoadDll', 'RtlMoveMemory ', 'RtlCopyMemory', 'SetPropA',
                              'WaitForSingleObjectEx', 'WaitForMultipleObjects', 'WaitForMultipleObjectsEx',
                              'KeInsertQueueApc', 'Wow64SetThreadContext', 'NtSuspendProcess', 'NtResumeProcess',
                              'DuplicateToken', 'NtReadVirtualMemoryEx', 'CreateProcessInternal',
                              'CreateProcessInternalW', 'EnumSystemLocalesA',
                              'UuidFromStringA'],
               'Evasion ': ['CreateFileMappingA', 'DeleteFileA', 'DeleteFileW', 'GetModuleHandleA', 'GetProcAddress',
                            'LoadLibraryA', 'LoadLibraryW',
                            'LoadLibraryExA', 'LoadResource', 'SetEnvironmentVariableA', 'SetFileTime', 'Sleep',
                            'WaitForSingleObject ', 'SetFileAttributesA ', 'SleepEx ', 'NtDelayExecution',
                            'NtWaitForMultipleObjects', 'NtWaitForSingleObject', 'CreateWindowExA', 'RegisterHotKey',
                            'timeSetEvent', 'IcmpSendEcho', 'WaitForSingleObjectEx', 'WaitForMultipleObjects',
                            'WaitForMultipleObjectsEx', 'SetWaitableTimer', 'CreateTimerQueueTimer',
                            'CreateWaitableTimer', 'SetTimer', 'Select', 'ImpersonateLoggedOnUser', 'SetThreadToken',
                            'DuplicateToken', 'SizeOfResource', 'LockResource', 'CreateProcessInternal',
                            'CreateProcessInternalW', 'TimeGetTime',
                            'EnumSystemLocalesA', 'UuidFromStringA', 'CryptProtectData'],
               'Spying ': ['AttachThreadInput', 'CallNextHookEx', 'GetAsyncKeyState', 'GetClipboardData', 'GetDC',
                           'GetDCEx', 'GetForegroundWindow', 'GetKeyboardState', 'GetKeyState', 'GetMessageA',
                           'GetRawInputData', 'GetWindowDC', 'MapVirtualKeyA', 'MapVirtualKeyExA', 'PeekMessageA',
                           'PostMessageA', 'PostThreadMessageA', 'RegisterHotKey', 'RegisterRawInputDevices',
                           'SendMessageA', 'SendMessageCallbackA', 'SendMessageTimeoutA', 'SendNotifyMessageA',
                           'SetWindowsHookExA', 'SetWindowsHookExW', 'SetWinEventHook', 'UnhookWindowsHookEx', 'BitBlt',
                           'StretchBlt',
                           'GetKeynameTextA'],
               'Internet ': ['WinExec', 'FtpPutFileA', 'HttpOpenRequestA', 'HttpSendRequestA', 'HttpSendRequestExA',
                             'InternetCloseHandle', 'InternetOpenA', 'InternetOpenUrlA', 'InternetOpenUrlW',
                             'InternetReadFile',
                             'InternetReadFileExA', 'InternetWriteFile', 'URLDownloadToFile', 'URLDownloadToFileW',
                             'URLDownloadToCacheFile',
                             'URLOpenBlockingStream', 'URLOpenStream', 'Accept', 'Bind', 'Connect', 'Gethostbyname',
                             'Inet_addr', 'Recv', 'Send', 'WSAStartup', 'Gethostname', 'Socket', 'WSACleanup', 'Listen',
                             'ShellExecuteA', 'ShellExecuteExA', 'ShellExecuteExW', 'DnsQuery_A', 'DnsQueryEx',
                             'WNetOpenEnumA',
                             'FindFirstUrlCacheEntryA', 'FindNextUrlCacheEntryA', 'InternetConnectA',
                             'InternetSetOptionA', 'WSASocketA', 'Closesocket', 'WSAIoctl', 'ioctlsocket',
                             'HttpAddRequestHeaders'],
               'Anti-Debugging ': ['CreateToolhelp32Snapshot', 'GetLogicalProcessorInformation',
                                   'GetLogicalProcessorInformationEx', 'GetTickCount', 'OutputDebugStringA',
                                   'CheckRemoteDebuggerPresent', 'Sleep', 'GetSystemTime', 'GetComputerNameA',
                                   'SleepEx ', 'IsDebuggerPresent', 'GetUserNameA', 'NtQueryInformationProcess',
                                   'ExitWindowsEx', 'FindWindowA', 'FindWindowW', 'FindWindowExA',
                                   'GetForegroundWindow',
                                   'GetTickCount64', 'QueryPerformanceFrequency', 'QueryPerformanceCounter',
                                   'GetNativeSystemInfo', 'RtlGetVersion', 'GetSystemTimeAsFileTime',
                                   'CountClipboardFormats'],
               'Ransomware ': ['CryptAcquireContextA', 'EncryptFileA', 'CryptEncrypt', 'CryptDecrypt',
                               'CryptCreateHash', 'CryptHashData', 'CryptDeriveKey', 'CryptSetKeyParam',
                               'CryptGetHashParam ', 'CryptDestroyKey', 'CryptGenRandom', 'DecryptFileA',
                               'FlushEfsCache', 'GetLogicalDrives', 'GetDriveTypeA', 'CryptStringToBinary ',
                               'CryptBinaryToString', 'CryptReleaseContext', 'CryptDestroyHash', 'EnumSystemLocalesA',
                               'CryptProtectData'],
               'Helper ': ['ConnectNamedPipe', 'CopyFileA', 'CreateFileA', 'CreateMutexA', 'CreateMutex',
                           'CreateMutexExA',
                           'DeviceIoControl', 'FindResourceA', 'FindResourceExA', 'GetModuleBaseNameA',
                           'GetModuleFileNameA', 'GetModuleFileNameExA', 'GetTempPathA', 'IsWoW64Process', 'MoveFileA',
                           'MoveFileExA', 'PeekNamedPipe', 'WriteFile', 'TerminateThread', 'CopyFile2', 'CopyFileExA',
                           'CopyFileExW',
                           'CreateFile2', 'CreateFileW', 'GetTempFileNameA', 'TerminateProcess', 'SetCurrentDirectory',
                           'FindClose',
                           'SetThreadPriority', 'UnmapViewOfFile', 'ControlService', 'ControlServiceExA',
                           'CreateServiceA', 'CreateServiceW', 'DeleteService', 'OpenSCManagerA', 'OpenSCManagerW',
                           'OpenServiceA', 'OpenServiceW', 'RegOpenKeyA',
                           'RegOpenKeyExA', 'RegOpenKeyExW', 'StartServiceA', 'StartServiceW',
                           'StartServiceCtrlDispatcherA', 'RegCreateKeyExA', 'RegCreateKeyExW',
                           'RegCreateKeyA', 'RegSetValueExA', 'RegSetValueExW', 'RegSetKeyValueA', 'RegDeleteValueA ',
                           'RegEnumKeyExA', 'RegEnumKeyExW',
                           'RegEnumValueA', 'RegEnumValueW', 'RegGetValueA', 'RegFlushKey', 'RegGetKeySecurity',
                           'RegLoadKeyA',
                           'RegLoadMUIStringA', 'RegOpenCurrentUser', 'RegOpenKeyTransactedA', 'RegOpenUserClassesRoot',
                           'RegOverridePredefKey', 'RegReplaceKeyA', 'RegRestoreKeyA', 'RegSaveKeyA', 'RegSaveKeyExA',
                           'RegSetKeySecurity', 'RegUnLoadKeyA', 'RegConnectRegistryA', 'RegCopyTreeA',
                           'RegCreateKeyTransactedA', 'RegDeleteKeyA', 'RegDeleteKeyW', 'RegDeleteKeyExA',
                           'RegDeleteKeyTransactedA',
                           'RegDeleteKeyValueA', 'RegDeleteTreeA', 'RegDeleteValueA', 'RegCloseKey', 'NtClose',
                           'NtCreateFile', 'NtDeleteKey', 'NtDeleteValueKey', 'NtMakeTemporaryObject',
                           'NtSetContextThread', 'NtSetInformationProcess', 'NtSetInformationThread',
                           'NtSetSystemEnvironmentValueEx', 'NtSetValueKey', 'NtShutdownSystem', 'NtTerminateProcess',
                           'NtTerminateThread', 'RtlSetProcessIsCritical', 'DrawTextExA', 'GetDesktopWindow',
                           'SetClipboardData', 'SetWindowLongA', 'SetWindowLongPtrA', 'OpenClipboard',
                           'SetForegroundWindow', 'BringWindowToTop', 'SetFocus', 'ShowWindow', 'NetShareSetInfo ',
                           'NetShareAdd', 'NtQueryTimer', 'GetIpNetTable', 'GetLogicalDrives', 'GetDriveTypeA',
                           'CreatePipe', 'RegEnumKeyA', 'WNetOpenEnumA', 'WNetEnumResourceA', 'WNetAddConnection2A',
                           'CallWindowProcA', 'NtResumeProcess', 'lstrcatA', 'ImpersonateLoggedOnUser',
                           'SetThreadToken', 'SizeOfResource', 'LockResource', 'UuidFromStringA', 'ExitProcess',
                           'MoveFileWithProgressW', 'OpenMutexW', ]}

# 补充our apis
